version: "3.9"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
        -   8098:80
        links:
            -   fpm
        volumes:
        -   ./:/var/www/messanger

    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        container_name: php7
        volumes:
        -   ./:/var/www/messanger
        links:
            -   mysql

    mysql:
        image: mysql:5.7
        ports:
        -   33061:3306
        volumes:
        -   ./dump:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=messanger_db
            - TZ=Europe/Moscow
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+03:00']

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
        -   8099:80
        links:
            -   mysql:mysql
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
            - PHP_UPLOAD_MAX_FILESIZE=100MB

